# Generated by Django 5.2.1 on 2025-06-09 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecins', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_dossier', models.CharField(blank=True, max_length=50, null=True)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('allergie_medicament', models.TextField(blank=True, null=True)),
                ('allergie_alimentaire', models.TextField(blank=True, null=True)),
                ('allergie_autre', models.TextField(blank=True, null=True)),
                ('maladies_chroniques', models.TextField(blank=True, null=True)),
                ('chirurgies', models.TextField(blank=True, null=True)),
                ('traitement_medicament', models.TextField(blank=True, null=True)),
                ('traitement_posologie', models.TextField(blank=True, null=True)),
                ('vaccin_covid', models.CharField(blank=True, max_length=50, null=True)),
                ('vaccin_hepatite_b', models.CharField(blank=True, max_length=50, null=True)),
                ('groupe_sanguin', models.CharField(blank=True, max_length=3, null=True)),
                ('rhesus', models.CharField(blank=True, max_length=10, null=True)),
                ('tension_arterielle', models.CharField(blank=True, max_length=20, null=True)),
                ('frequence_cardiaque', models.CharField(blank=True, max_length=20, null=True)),
                ('temperature', models.CharField(blank=True, max_length=20, null=True)),
                ('poids', models.CharField(blank=True, max_length=10, null=True)),
                ('contact_urgence_nom', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_urgence_telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_urgence_lien', models.CharField(blank=True, max_length=50, null=True)),
                ('medecin_referent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medecins.profilmedecin')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dossier', to='patients.patient')),
            ],
        ),
    ]
